version: 2.1

jobs:
  test-and-lint:
    working_directory: ~/colearnapp
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout:
          path: ~/colearnapp
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: lint
          command: pylint my_media/ media_organizer/
      - run:
          name: run tests
          command: python manage.py test

workflows:
  build-and-test-workflow:
    jobs:
      - test-and-lint
